### PR TITLE
migrate kodiak UI from circleci to GitHub actions

### PR DESCRIPTION
**Pull request by alexanderchan**
This migrates the circleci config to github actions.

**Main Story:** [ch73758](https://app.clubhouse.io/skyverge/story/73758/migrate-kodiak-ui-from-circleci-to-github-actions)

<a name="qa"></a>

## Acceptance Crtieria

- [x] test runs on pull request

## Deployment

- check after this pr merged
- [ ] test runs on merge to master
- [x] Circle CI no longer builds -- use the "stop building" option in [configuration](https://app.circleci.com/settings/project/github/skyverge/kodiak-ui)

### CODE REVIEW

**Comment by alexanderchan** [comment]
@justinstern this looks like it's running now, would you be able to set the configuration in the admin to stop building on the [kodiak-ui config on circle ci](https://app.circleci.com/settings/project/github/skyverge/kodiak-ui)?

**Comment by justinstern** [comment]
> would you be able to set the configuration in the admin to stop building on the kodiak-ui config on circle ci?

@alexanderchan done!

**Comment by achan-godaddy** [comment]
@justinstern looks great thanks!

**Review by wesleycole — APPROVED** [review]
Looks great!!

**Pull request merged**
